language: go
go_import_path: github.com/t11e/xmlpicker
go:
  - 1.7.x
  - 1.8.x
  - tip

script:
  - go test $(go list ./... | grep -v /vendor/)

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/v0.12.3 && go install && cd -
  - glide install --strip-vendor
